apiVersion: ocpctl.open-control-plane.io/v1alpha1
kind: Environment
spec:
  namespace: openmcp-system
  operator:
    # renovate: datasource=docker depName=ghcr.io/openmcp-project/images/openmcp-operator
    image: ghcr.io/openmcp-project/images/openmcp-operator:v1.1.0
  clusterProviders:
    - name: kind
      # renovate: datasource=docker depName=ghcr.io/openmcp-project/images/cluster-provider-kind
      image: ghcr.io/openmcp-project/images/cluster-provider-kind:v0.4.2
  serviceProviders:
    - name: crossplane
      # renovate: datasource=docker depName=ghcr.io/openmcp-project/images/service-provider-crossplane
      image: ghcr.io/openmcp-project/images/service-provider-crossplane:v1.0.1
  platformServices:
    - name: gateway
      # renovate: datasource=docker depName=ghcr.io/openmcp-project/images/platform-service-gateway
      image: ghcr.io/openmcp-project/images/platform-service-gateway:v0.0.12
